In [116]:
import numpy as np
import pandas as pd


In [117]:
df=pd.read_csv("D:/Data_set/Mumbai House Prices.csv.zip")
df.head()

,bhk,type,locality,area,price,price_unit,region,status,age
0,3,Apartment,Lak And Hanware The Residency Tower,685,2.50,Cr,Andheri West,Ready to move,New
1,2,Apartment,Radheya Sai Enclave Building No 2,640,52.51,L,Naigaon East,Under Construction,New
2,2,Apartment,Romell Serene,610,1.73,Cr,Borivali West,Under Construction,New
3,2,Apartment,Soundlines Codename Urban Rainforest,876,59.98,L,Panvel,Under Construction,New
4,2,Apartment,Origin Oriana,659,94.11,L,Mira Road East,Under Construction,New


In [118]:
df.isnull().sum()

bhk           0
type          0
locality      0
area          0
price         0
price_unit    0
region        0
status        0
age           0
dtype: int64

In [119]:
df['type'].value_counts()

type
Apartment            74854
Studio Apartment       882
Villa                  226
Independent House       73
Penthouse                3
Name: count, dtype: int64

In [120]:
df['locality'].value_counts()

locality
Hiranandani Meadows         861
Sheth Avalon                516
T Bhimjyani The Verraton    499
ACME Ozone Phase 2          467
Runwal Gardens              389
                           ... 
Cosmos Angel Tower            1
Sheth Konark Empress          1
Shree Chamunda Garden         1
Vega Platinum Enclave         1
Omkar Puram                   1
Name: count, Length: 9782, dtype: int64

In [121]:
df['price_unit'].value_counts()

price_unit
Cr    40981
L     35057
Name: count, dtype: int64

In [122]:
# df['region'].value_counts()
regions = sorted(df['region'].unique())


In [123]:
df['age'].value_counts()

age
New        38072
Resale     23357
Unknown    14609
Name: count, dtype: int64

In [124]:
df.drop('locality',axis=1,inplace=True)
df

,bhk,type,area,price,price_unit,region,status,age
0,3,Apartment,685,2.50,Cr,Andheri West,Ready to move,New
1,2,Apartment,640,52.51,L,Naigaon East,Under Construction,New
2,2,Apartment,610,1.73,Cr,Borivali West,Under Construction,New
3,2,Apartment,876,59.98,L,Panvel,Under Construction,New
4,2,Apartment,659,94.11,L,Mira Road East,Under Construction,New
...,...,...,...,...,...,...,...,...
76033,3,Apartment,1527,7.00,Cr,Juhu,Ready to move,Unknown
76034,5,Apartment,3049,12.00,Cr,Juhu,Ready to move,Unknown
76035,4,Apartment,3313,10.00,Cr,Napeansea Road,Ready to move,Unknown
76036,2,Apartment,1305,4.25,Cr,Bandra East,Ready to move,Unknown


In [125]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
categorical_cols=['type','price_unit','status','status','region','age']
for col in categorical_cols:
    df[col]=label_encoder.fit_transform(df[col])

In [126]:
df

,bhk,type,area,price,price_unit,region,status,age
0,3,0,685,2.50,0,8,0,0
1,2,0,640,52.51,1,124,1,0
2,2,0,610,1.73,0,31,1,0
3,2,0,876,59.98,1,140,1,0
4,2,0,659,94.11,1,117,1,0
...,...,...,...,...,...,...,...,...
76033,3,0,1527,7.00,0,69,0,2
76034,5,0,3049,12.00,0,69,0,2
76035,4,0,3313,10.00,0,128,0,2
76036,2,0,1305,4.25,0,18,0,2


In [127]:
x=df.drop('price',axis=1)
y=df['price']

In [128]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [129]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)
x_train_scaled

array([[-1.10311778, -0.12233878, -0.91487076, ...,  1.50452444,
         1.20254542, -0.89303621],
       [-1.10311778, -0.12233878, -0.28909648, ...,  0.0263611 ,
         1.20254542, -0.89303621],
       [ 2.15756387, -0.12233878,  0.92982878, ...,  0.48828714,
        -0.83156942, -0.89303621],
       ...,
       [-0.0162239 , -0.12233878, -0.20012383, ..., -1.54418745,
        -0.83156942,  1.69293003],
       [-1.10311778, -0.12233878, -0.55453154, ..., -1.6519702 ,
        -0.83156942,  0.39994691],
       [ 1.07066999, -0.12233878,  0.55614367, ...,  0.0263611 ,
        -0.83156942, -0.89303621]], shape=(60830, 7))

# Model Training

In [131]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train_scaled,y_train)
y_pred=lr.predict(x_test_scaled)
y_pred

array([60.83022567,  5.1119344 , 59.20052767, ..., 10.80915249,
        1.40468192, 66.03058627], shape=(15208,))

In [132]:
from sklearn.metrics import r2_score,mean_absolute_error
mean_absolute_error(y_test,y_pred)

10.083095269233956

In [133]:
r2_score(y_test,y_pred)

0.7981083274492443

In [134]:
from sklearn.linear_model import Ridge
r=Ridge()
r.fit(x_train_scaled,y_train)
y_pred=r.predict(x_test_scaled)
y_pred

array([60.83002162,  5.11216877, 59.20022808, ..., 10.8088684 ,
        1.40552091, 66.02956252], shape=(15208,))

In [135]:
from sklearn.metrics import r2_score,mean_absolute_error

print(mean_absolute_error(y_test,y_pred))

print(r2_score(y_test,y_pred))

10.082936311197377
0.7981082651180786


In [136]:
from sklearn.linear_model import Lasso
ls=Lasso()
ls.fit(x_train_scaled,y_train)
y_pred=ls.predict(x_test_scaled)
y_pred

array([58.75404141,  4.97929549, 58.75404141, ...,  7.96095447,
        2.26303955, 61.73570039], shape=(15208,))

In [137]:
from sklearn.metrics import r2_score,mean_absolute_error

print(mean_absolute_error(y_test,y_pred))

print(r2_score(y_test,y_pred))

9.63937844862152
0.7904499866023833


In [138]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error
xgb = XGBRegressor(
    n_estimators=800,
    learning_rate=0.03,
    max_depth=5,
    subsample=0.9,
    colsample_bytree=0.9
)
xgb.fit(x_train, y_train)
y_pred = xgb.predict(x_test)

# evaluate
print("XGB R2:", r2_score(y_test, y_pred))
print("XGB MAE:", mean_absolute_error(y_test, y_pred))


XGB R2: 0.9602586385796077
XGB MAE: 3.590804919178795


In [139]:
import pickle
pickle.dump(xgb,open("D:/Model/house_price.pkl","wb"))

In [140]:
df.head()

,bhk,type,area,price,price_unit,region,status,age
0,3,0,685,2.50,0,8,0,0
1,2,0,640,52.51,1,124,1,0
2,2,0,610,1.73,0,31,1,0
3,2,0,876,59.98,1,140,1,0
4,2,0,659,94.11,1,117,1,0


In [141]:
import numpy as np
def predict(bhk, type, area, price_unit, region, status, age):
    feature = np.array([[bhk,type,area,price_unit,region,status,age]])
    result = xgb.predict(feature)
    return result[0]


In [142]:
df.iloc[0]

bhk             3.0
type            0.0
area          685.0
price           2.5
price_unit      0.0
region          8.0
status          0.0
age             0.0
Name: 0, dtype: float64

In [143]:
bhk=3.0
type=0.0
area=685.0
price_unit=0.0
region=8.0
status=0.0
age=0.0
result=predict(bhk, type, area, price_unit, region, status, age)
print(result)

2.340708


In [1]:
import os
print(os.getcwd())

C:\Users\lenovo\scikit_learn
